[versions]
kotlin = "2.4.20"
agp = "9.4.1"
libxposedApi = "102.0.0"
appcompat = "1.8.0"
material = "1.14.0"
activity = "1.13.0"
core = "1.19.1"

[libraries]
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
core = { module = "androidx.core:core", version.ref = "core" }
libxposed-api = { module = "io.github.libxposed:api", version.ref = "libxposedApi" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
